propose adr 0003 for workspace blob caching
weaveworks/tf-controller pull request #1010
Opened 2023-09-20 13:58 UTC by chanwit

2023-09-20 14:13 UTC, yitsushi approved these changes

2023-09-20 14:13 UTC, yitsushi commented on docs/adr/0003-workspace-blob-caching.md
> +   * Each Workspace Blob will be cached on the TF-Controller's local disk, following the naming convention `$namespace-$name.tar.gz`.
By default it seems reasonable, but I would like to note, it can still cause scenarios when we still hit the "unable to delete" issue. If the controller container was restarted while the source was deleted (for example the controller crashed or rescheduled on a different node), it will not able to retrieve blob cache or blob artifact data from source.

2023-09-20 14:13 UTC, yitsushi commented on docs/adr/0003-workspace-blob-caching.md
> +   * Each Workspace Blob will be cached on the TF-Controller's local disk, following the naming convention `$namespace-$name.tar.gz`.
Another note: in the `finalizer` we have to delete cache files to avoid cache collision or malicious access to cache, if a resource was deleted, it is possible to recreate resources with the same name. If a potentially attacker can create resources with the same name, they can access the original blob content for example with break-the-glass. I don't say it's highly probable, but most intrusions exploit a series of issues (in this case, they can create resources in that namespace somehow).

And of course it's not just security, but we don't want to reuse a different cache file on the first iteration just because we have `foo-bar.tar.gz` on the filesystem.

2023-09-20 14:13 UTC, yitsushi commented
Added some notes, but the doc itself looks good to me.

2023-09-20 14:23 UTC, chanwit commented on docs/adr/0003-workspace-blob-caching.md
> +   * Each Workspace Blob will be cached on the TF-Controller's local disk, following the naming convention `$namespace-$name.tar.gz`.
> If the controller container was restarted while the source was deleted (for example the controller crashed or rescheduled on a different node), it will not able to retrieve blob cache or blob artifact data from source.

yep, we'll adopt a PVC mechanism similar to the Source Controller for the future implementation.

2023-09-20 14:34 UTC, yitsushi submitted a review, later dismissed

2023-09-21 10:06 UTC, squaremo requested changes
This ADR needs to be precise about the problem it addresses and how it addresses it. At present it gives its rationale in terms of adjectives -- "streamlined", "efficient", "optimized" -- but

 1. it's not clear why optimising is important, except in general terms
 2. the claims aren't supported by the explanation of the design

I suggest you revisit the context, and explain what is the "resource deletion problem" and what effect it has for users. Then you can rephrase the explanation of the design in terms of how it breaks down that problem, mechanically.

2023-09-21 10:48 UTC, yitsushi commented on docs/adr/0003-workspace-blob-caching.md
> +   * To prevent unauthorized access to the cache entries, and cache collisions, the cache file will be deleted after the finalization process is complete.
That (and the previous line) prevents the scenario I described earlier.

2023-10-09 13:11 UTC, yitsushi submitted a review, later dismissed

2023-10-09 13:17 UTC, chanwit commented on docs/adr/0003-workspace-blob-caching.md
> +   * Security measures will ensure the safety of the stored BLOBs, minimizing potential threats.
> the added parts will be secure, but there's no overall change
yes.

2023-10-09 13:39 UTC, yitsushi approved these changes

2023-10-09 15:33 UTC, squaremo approved these changes
Thanks for adding the explanation of the problem. The text reads better as an argument, now -- here's the problem, we're going to solve it this way, because ...".

I was tripped up by the sentence "If we try to remove [a Terraform object] without deleting these resources [it relies on], the TF object gets stuck in an inconsistent state [...]" -- but I may have misunderstood. Revise it if you can see what I mean in my comment :-)

2023-10-09 15:33 UTC, squaremo commented on docs/adr/0003-workspace-blob-caching.md
> +Deleting a single TF object can sometimes be obstructed because it's tied to other resources like Source objects, Secrets, and ConfigMaps. If we try to remove it without deleting these resources, the
Based on the solution given below I would expect the problem to be that a Terraform object can't be finalized if resources it depends on are deleted _before_ it is. The description here suggests vice versa: that deleting a Terraform object before the things it relies on leads to the problem. Have I misunderstood?

2023-10-09 15:33 UTC, squaremo commented on docs/adr/0003-workspace-blob-caching.md
> +Currently, the TF-Controller downloads a Source BLOB and pushes it to a tf-runner. The tf-runner processes this BLOB to create a Workspace file system. It generates a backend configuration file, vari
>  This newly created Workspace file system is then compressed, sent back to the TF-Controller, and stored as a Workspace BLOB in the controller's storage.

This is given as part of the solution below -- "A gRPC function named `CreateWorkspaceBlob` will be invoked by the TF-Controller to tell tf-runner to compress the Workspace file system into a tar.gz BLOB, which is then retrieved back to the controller". Is it current behaviour, or proposed behaviour?

2023-10-09 15:33 UTC, squaremo commented on docs/adr/0003-workspace-blob-caching.md
> +Therefore, the TF-Controller is being enhanced to address this problem more efficiently, using the contents of generated Workspace BLOBs. Each BLOB contains all necessary information from the associa
What is it more efficient than?

If I'm a user that has got into this situation of having an undeletable Terraform object, is there anything I can do to unstick it -- presumably, recreating the missing resources would work, right? If so, I think you should mention that here or as part of the explanation of the problem; and, say that the proposed solution makes it much less likely that a user will have to step in and fix things themselves. (That really would be more efficient!)

2023-10-11 10:29 UTC, merged

2023-10-11 10:29 UTC, chanwit commented
Will do a follow-up PR to address your comments.