[WIP] feat: add webhook receiver server
weaveworks/tf-controller pull request #579
Opened 2023-04-26 12:06 UTC by yitsushi

progress:
* It can listen on a port set by a cli flag.
* It has a logger, similar logic as we have in other services (wgo oss, wge, progressive delivery, pipeline controller).
* It can receive webhook requests on `/callback`. Not the root, case we need more endpoints, it will be easier to just and new ones instead of moveing existing part over or even send out a "breaking changes" notice.
* Validates the request. The secret key is coming from the `WEBHOOK_HMAC_KEY` environment variable.

Closes #578

References:
* https://github.com/weaveworks/tf-controller/issues/578
* https://github.com/weaveworks/tf-controller/issues/577
* https://github.com/weaveworks/tf-controller/issues/576

2023-04-26 12:49 UTC, yitsushi commented
```
❯ WEBHOOK_HMAC_KEY="xxxx" go run ./cmd/webhook-receiver --log-level debug
{"level":"info","ts":"2023-04-26T14:48:16.877+0200","msg":"Starting server","kind":"webhook","addr":"[::]:8080"}
{"level":"debug","ts":"2023-04-26T14:48:47.189+0200","msg":"incoming hmac requesr is valid","organization":"yitsushi","repository":"webhook-tester","kind":"issue_comment"}
```

2023-04-26 14:35 UTC, chanwit commented
Thank you @yitsushi 

Overall, it looks good to me. You also used `logr` and Flux's log packages to handle logging, which is great. 
Please continue with the next steps.

2023-04-26 16:10 UTC, yitsushi commented
Now it's ready for a full review.

2023-04-26 17:51 UTC, chanwit requested changes
Thank you for writing a comprehensive set of tests @yitsushi :1st_place_medal:

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	testCases := []struct {
```suggestion
	g := NewGomegaWithT(t)

	testCases := []struct {
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	var log logr.Logger = buflogr.NewWithBuffer(&buf)
```suggestion
	var (
		buf bytes.Buffer
		log = buflogr.NewWithBuffer(&buf)
	)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +			assert.Contains(t, buf.String(), testCase.logContains)
```suggestion
			g.Expect(responseRecorder.Code).To(Equal(testCase.code))
			g.Expect(buf.String()).To(ContainSubstring(testCase.logContains))
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	os.Setenv("WEBHOOK_HMAC_KEY", webhookSecret)
```suggestion
	g := NewGomegaWithT(t)

	os.Setenv("WEBHOOK_HMAC_KEY", webhookSecret)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	var log logr.Logger = buflogr.NewWithBuffer(&buf)
```suggestion
	var (
		buf bytes.Buffer
		log = buflogr.NewWithBuffer(&buf)
	)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	}
```suggestion
	g.Expect(err).NotTo(HaveOccurred())
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	assert.Contains(t, buf.String(), "missing hmac signature")
```suggestion
	g.Expect(responseRecorder.Code).To(Equal(http.StatusUnauthorized))
	g.Expect(buf.String()).To(ContainSubstring("missing hmac signature"))
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	os.Setenv("WEBHOOK_HMAC_KEY", "invalid-key")
```suggestion
	g := NewGomegaWithT(t)

	os.Setenv("WEBHOOK_HMAC_KEY", "invalid-key")
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	var log logr.Logger = buflogr.NewWithBuffer(&buf)
```suggestion
	var (
		buf bytes.Buffer
		log = buflogr.NewWithBuffer(&buf)
	)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	}
```suggestion
	g.Expect(err).NotTo(HaveOccurred())
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	assert.Contains(t, buf.String(), "invalid webhook signature parsing webhook request")
```suggestion
	g.Expect(responseRecorder.Code).To(Equal(http.StatusBadRequest))
	g.Expect(buf.String()).To(ContainSubstring("invalid webhook signature parsing webhook request"))
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	os.Setenv("WEBHOOK_HMAC_KEY", webhookSecret)
```suggestion
	g := NewGomegaWithT(t)

	os.Setenv("WEBHOOK_HMAC_KEY", webhookSecret)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	var log logr.Logger = buflogr.NewWithBuffer(&buf)
```suggestion
	var (
		buf bytes.Buffer
		log = buflogr.NewWithBuffer(&buf)
	)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	}
```suggestion
	g.Expect(err).NotTo(HaveOccurred())
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	assert.Contains(t, buf.String(), "incoming hmac request is valid kind pull_request")
```suggestion
	g.Expect(responseRecorder.Code).To(Equal(http.StatusAccepted))
	g.Expect(buf.String()).To(ContainSubstring("incoming hmac request is valid kind pull_request"))
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	os.Setenv("WEBHOOK_HMAC_KEY", webhookSecret)
```suggestion
	g := NewGomegaWithT(t)

	os.Setenv("WEBHOOK_HMAC_KEY", webhookSecret)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	var log logr.Logger = buflogr.NewWithBuffer(&buf)
```suggestion
	var (
		buf bytes.Buffer
		log = buflogr.NewWithBuffer(&buf)
	)
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	}
```suggestion
	g.Expect(err).NotTo(HaveOccurred())
```

2023-04-26 17:51 UTC, chanwit commented on internal/server/webhook/callback_handler_test.go
> +	assert.Contains(t, buf.String(), "incoming hmac request is valid kind issue_comment")
```suggestion
	g.Expect(responseRecorder.Code).To(Equal(http.StatusAccepted))
	g.Expect(buf.String()).To(ContainSubstring("incoming hmac request is valid kind issue_comment"))
```

2023-04-27 08:17 UTC, yitsushi commented
Thank you, for the review, updated the tests to use `gomega`. Did not apply comments one by one, because:
- It was easier to just replace it in vim than pressing the "add to batch" button on all comments.
- I had a slight modification on suggestion, so I would have to make a new commit anyway.

2023-04-27 11:22 UTC, chanwit commented
No worries @yitsushi :-)

2023-04-27 11:22 UTC, chanwit approved these changes
LGTM thank you @yitsushi :1st_place_medal:

2023-04-27 13:41 UTC, chanwit commented
ping @yiannistri

2023-04-27 18:16 UTC, chanwit commented
I'll go ahead merging this so we can continue on the next thing.

2023-04-27 18:16 UTC, merged